spring:
  cloud:
    stream:
      function:
        bindings:
          consume-in-0: input
      bindings:
        input:
          binder: kafka
          destination: usage-cost
  main:
    allow-bean-definition-overriding: true
