server:
  port: 9091
spring:
  cloud:
    stream:
      function:
        bindings:
          sendEvents-out-0 : output
      bindings:
        output:
          binder: kafka
          destination: usage-detail
  main:
    allow-bean-definition-overriding: true