server:
  port: 9092
spring:
  cloud:
    stream:
      function:
        bindings:
          processUsageCost-in-0: input
          processUsageCost-out-0: output
      bindings:
        input:
          binder: kafka
          destination: usage-detail
        output:
          kafka: kafka
          destination: usage-cost